version: '3.8'
services:
  products-api:
    build:
      context: .
      dockerfile: src/Products.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development